Nv feat/035
CodenityOrg/nearvice-api pull request #19
Opened 2020-03-27 22:40 UTC by CristianPeralta

2020-03-27 22:59 UTC, AngelRodRo submitted a review, later dismissed

2020-04-06 16:49 UTC, florenperetti requested changes

2020-04-06 16:49 UTC, florenperetti commented on controllers/userController.js
> +    const expiresIn = keepMe ? 7 * 24 * 60 * 60 : 1 * 24 * 60 * 60;
change this to final result to avoid calculating every time

2020-04-06 20:41 UTC, AngelRodRo commented on controllers/userController.js
> +    const expiresIn = keepMe ? 7 * 24 * 60 * 60 : 1 * 24 * 60 * 60;
I think it's okay. Does it repercute on performance? 🤔

2020-04-06 20:41 UTC, AngelRodRo submitted a review, later dismissed

2020-04-07 14:00 UTC, florenperetti approved these changes

2020-04-07 14:00 UTC, merged